LifeSaver/LifeSaver/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls', namespace="app")),

]

LifeSaver/app/urls.py
from django.conf.urls import url
from django.urls import path
from .views import index, notifications, user, map, help, VictimSignup, VictimLogin, help_food, help_shelter, help_funding, needsHelp, notVictim
app_name = "app"

urlpatterns = [
    path('', index, name="index"),
    path('user', user, name="user"),
    path('notifications', notifications, name="notifications"),
    path('map', map, name="map"),
    path('help', help, name="help"),
    path('victimSignup', VictimSignup, name="victimSignup"),
    path('victimLogin', VictimLogin, name="victimLogin"),
    path('help-food', help_food, name="help_food"),
    path('help-shelter', help_shelter, name="help_shelter"),
    path('help-funding', help_funding, name="help_funding"),
    path('need-help', needsHelp, name="needsHelp"),
    path('notVictim', notVictim, name="notVictim"),
]

LifeSaver/app/templates/app/geofence.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA7i1Xt81SPU4iq-Y-g4Z5WRj6bXvBvjqg&callback=myMap"></script>
<script src="../../static/demo/geofence.js" type="text/javascript">
         google.load("maps", "3",{other_params:"sensor=false&libraries=geometry"});
      //   function myMap() {
      //   var mapProp= {
      //       center:new google.maps.LatLng(19.0084743,72.8246082),
      //       zoom:14,
      //   };
      //   var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
      // }
</script>

<body style="margin:0px; padding:0px;" >

 <select id="radius_km">
	 <option value=1>1km</option>
	 <option value=2>2km</option>
	 <option value=5>5km</option>
	 <option value=30>30km</option>
 </select>
 <div id="map_canvas"  style="width:500px; height:300px;">
</body>

LifeSaver/app/templates/app/help.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../../static/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../../static/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Life Saver
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport'
  />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"
  />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="../../static/css/material-dashboard.css?v=2.1.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="../../static/demo/demo.css" rel="stylesheet" />
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="../../static/img/sidebar-1.jpg">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo">
        <a href="#" class="simple-text logo-normal">
          Life Saver
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item  ">
            <a class="nav-link" href="{% url 'app:index' %}">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:user' %}">
              <i class="material-icons">person</i>
              <p>User Profile</p>
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'app:help' %}">
              <i class="material-icons">help</i>
              <p>Help</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:map' %}">
              <i class="material-icons">location_ons</i>
              <p>Hospitals</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'app:notifications' %}">
              <i class="material-icons">notifications</i>
              <p>Notifications</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="notVictim">
              <i class="material-icons">notifications</i>
              <p>{{user.username}}</p>
            </a>
          </li>
          {% if victim %}
          <li class="nav-item ">
            <a class="nav-link" href="notVictim">
                <button class="btn btn-primary btn-block">I have been helped</button>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">Help</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notifications">5</span>
                  <p class="d-lg-none d-md-block">
                    Some Actions
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Mike John responded to your email</a>
                  <a class="dropdown-item" href="#">You have 5 new tasks</a>
                  <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                  <a class="dropdown-item" href="#">Another notifications</a>
                  <a class="dropdown-item" href="#">Another One</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->

      <div class="content">
        <div class="container-fluid">
          <div id="initialHelpDisplay" class="card">
            <div class="card-header card-header-primary text-center">
              <h3 class="card-title">Do you need help or want to help</h3>
            </div>
            <div class="col-md-12" style="margin-top: 20px;">
              <div class="places-buttons">
                <div class="row">
                  <div class="col-lg-8 col-md-10 ml-auto mr-auto">
                    <div class="row">
                      <div class="col-md-6">
                        <a href="need-help"><button class="btn btn-primary btn-block">I need help</button></a>
                      </div>
                      <div class="col-md-6">
                        <button class="btn btn-primary btn-block" onclick="demo.showWantsToHelp()">I want to help</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
            <div id="wantsToHelp" style="display: none;" class="card">
              <div class="col-md-12">
                <div class="places-buttons">
                  <div class="row">
                    <div class="col-lg-8 col-md-10 ml-auto mr-auto">
                      <div class="row"  style="margin-top: 20px;">
                        <div class="col-md-12">
                          <a href="help-food"><button class="btn btn-primary btn-block">Food</button></a>
                        </div>
                        <div class="col-md-12">
                          <a href="help-shelter"><button class="btn btn-primary btn-block">Shelter</button></a>
                        </div>
                        <div class="col-md-12">
                          <button class="btn btn-primary btn-block">Donate Blood</button>
                        </div>
                        <div class="col-md-12">
                          <button class="btn btn-primary btn-block">Offer Medical Assistance</button>
                        </div>
                        <div class="col-md-12">
                          <a href="help-funding"><button class="btn btn-primary btn-block">Crowd Funding</button></a>
                        </div>
                        <div class="col-md-12">
                          <button class="btn btn-primary btn-block">Offer Child Care</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>

      </div>

      <!-- <div id="map"></div> -->
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="../../static/js/core/jquery.min.js" type="text/javascript"></script>
  <script src="../../static/js/core/popper.min.js" type="text/javascript"></script>
  <script src="../../static/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
  <script src="../../static/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA7i1Xt81SPU4iq-Y-g4Z5WRj6bXvBvjqg"></script>
  <!-- Chartist JS -->
  <script src="../../static/js/plugins/chartist.min.js"></script>
  <!--  notifications Plugin    -->
  <script src="../../static/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="../../static/js/material-dashboard.min.js?v=2.1.0" type="text/javascript"></script>
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="../../static/demo/demo.js"></script>
  <script>
    $(document).ready(function () {
      // Javascript method's body can be found in static/js/demos.js
      demo.initGoogleMaps();
    });
  </script>
</body>

</html>

LifeSaver/app/templates/app/map.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../../static/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../../static/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Life Saver
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="../../static/css/material-dashboard.css?v=2.1.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="../../static/demo/demo.css" rel="stylesheet" />
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="../../static/img/sidebar-1.jpg">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo">
        <a href="#" class="simple-text logo-normal">
          Life Saver
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item  ">
            <a class="nav-link" href="{% url 'app:index' %}">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:user' %}">
              <i class="material-icons">person</i>
              <p>User Profile</p>
            </a>
          </li>
           <li class="nav-item ">
            <a class="nav-link" href="{% url 'app:help' %}">
              <i class="material-icons">help</i>
              <p>Help</p>
            </a>
          </li>
          <!--<li class="nav-item ">
            <a class="nav-link" href="./typography.html">
              <i class="material-icons">library_books</i>
              <p>Typography</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="./icons.html">
              <i class="material-icons">bubble_chart</i>
              <p>Icons</p>
            </a>
          </li> -->
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'app:map' %}">
              <i class="material-icons">location_ons</i>
              <p>Hospitals</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'app:notifications' %}">
              <i class="material-icons">notifications</i>
              <p>notifications</p>
            </a>
          </li>
          <!-- <li class="nav-item active-pro ">
                <a class="nav-link" href="./upgrade.html">
                    <i class="material-icons">unarchive</i>
                    <p>Upgrade to PRO</p>
                </a>
            </li> -->
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">Hospitals</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notifications">5</span>
                  <p class="d-lg-none d-md-block">
                    Some Actions
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Mike John responded to your email</a>
                  <a class="dropdown-item" href="#">You have 5 new tasks</a>
                  <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                  <a class="dropdown-item" href="#">Another notifications</a>
                  <a class="dropdown-item" href="#">Another One</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div id="map"></div>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="../../static/js/core/jquery.min.js" type="text/javascript"></script>
  <script src="../../static/js/core/popper.min.js" type="text/javascript"></script>
  <script src="../../static/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
  <script src="../../static/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA7i1Xt81SPU4iq-Y-g4Z5WRj6bXvBvjqg"></script>
  <!-- Chartist JS -->
  <script src="../../static/js/plugins/chartist.min.js"></script>
  <!--  notifications Plugin    -->
  <script src="../../static/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="../../static/js/material-dashboard.min.js?v=2.1.0" type="text/javascript"></script>
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="../../static/demo/demo.js"></script>
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in static/js/demos.js
      demo.initGoogleMaps();
    });
  </script>
</body>

</html>

LifeSaver/app/templates/app/need-help.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../../static/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../../static/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Life Saver
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport'
  />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"
  />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="../../static/css/material-dashboard.css?v=2.1.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="../../static/demo/demo.css" rel="stylesheet" />
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="../../static/img/sidebar-1.jpg">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo">
        <a href="#" class="simple-text logo-normal">
          Life Saver
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item  ">
            <a class="nav-link" href="{% url 'app:index' %}">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:user' %}">
              <i class="material-icons">person</i>
              <p>User Profile</p>
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'app:help' %}">
              <i class="material-icons">help</i>
              <p>Help</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:map' %}">
              <i class="material-icons">location_ons</i>
              <p>Hospitals</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'app:notifications' %}">
              <i class="material-icons">notifications</i>
              <p>Notifications</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="#">
              <i class="material-icons">user</i>
              <p>{{user.username}}</p>
            </a>
          </li>
          {% if victim %}
          <li class="nav-item ">
            <a class="nav-link" href="notVictim">
                <button class="btn btn-primary btn-block">I have been helped</button>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">Help</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">notifications</i>
                  <span class="notifications">5</span>
                  <p class="d-lg-none d-md-block">
                    Some Actions
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Mike John responded to your email</a>
                  <a class="dropdown-item" href="#">You have 5 new tasks</a>
                  <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                  <a class="dropdown-item" href="#">Another notifications</a>
                  <a class="dropdown-item" href="#">Another One</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->

      <div class="content">
        <div class="container-fluid">
              <div class="row">
                  <div class="col-md-12">
                    <div class="card">
                      <div class="card-header card-header-primary">
                        <h4 class="card-title ">NGO</h4>
                      </div>
                      <div class="card-body">
                        <div class="table-responsive">
                          <table class="table">
                            <thead class=" text-primary">
                              <th>
                                ID
                              </th>
                              <th>
                                Name
                              </th>
                              <th>
                                Address
                              </th>
                              <th>
                                Select
                              </th>
                            </thead>
                            <tbody>
                              <tr>
                                <td>
                                  1
                                </td>
                                <td>
                                  Dakota Rice
                                </td>
                                <td>
                                  Niger
                                </td>
                                <td>
                                  Oud-Turnhout
                                </td>
                                <td>
                                  <button class="btn btn-primary btn-block">Select</button>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12">
                      <div class="card">
                        <div class="card-header card-header-primary">
                          <h4 class="card-title ">People</h4>
                        </div>
                        <div class="card-body">
                          <div class="table-responsive">
                            <table class="table">
                              <thead class=" text-primary">
                                <th>
                                  ID
                                </th>
                                <th>
                                  Name
                                </th>
                                <th>
                                  Address
                                </th>
                                <th>
                                  Select
                                </th>
                              </thead>
                              <tbody>
                                <tr>
                                  <td>
                                    1
                                  </td>
                                  <td>
                                    Dakota Rice
                                  </td>
                                  <td>
                                    Niger
                                  </td>
                                  <td>
                                    Oud-Turnhout
                                  </td>
                                  <td>
                                    <button class="btn btn-primary btn-block">Select</button>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
        </div>

      </div>

      <!-- <div id="map"></div> -->
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="../../static/js/core/jquery.min.js" type="text/javascript"></script>
  <script src="../../static/js/core/popper.min.js" type="text/javascript"></script>
  <script src="../../static/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
  <script src="../../static/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA7i1Xt81SPU4iq-Y-g4Z5WRj6bXvBvjqg"></script>
  <!-- Chartist JS -->
  <script src="../../static/js/plugins/chartist.min.js"></script>
  <!--  notifications Plugin    -->
  <script src="../../static/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="../../static/js/material-dashboard.min.js?v=2.1.0" type="text/javascript"></script>
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="../../static/demo/demo.js"></script>
  <script>
    $(document).ready(function () {
      // Javascript method's body can be found in static/js/demos.js
      demo.initGoogleMaps();
    });
  </script>
</body>

</html>